/*
 * RPToolkit - Tools to assist Role-Playing Game masters and players
 * Copyright (C) 2016 Dane Zeke Liergaard
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package com.rptools.name;

import com.dzlier.markov.MarkovChain;
import java.util.Random;

/**
 * Wrapper for a {@link MarkovChain} that splits names into vowel/consonant pieces.
 * I.E. "LIERGAARD" -> "L" -> "IE" -> "RG" -> "AA" -> "RD"
 */
public class Names {

  private final MarkovChain<String, String> markovChain;
  private final Random random = new Random();

  public Names(MarkovChain<String, String> markovChain) {
    this.markovChain = markovChain;
  }

  /**
   * Generates a name from the {@link MarkovChain}, with look-behind depth provided.
   *
   * @param depth Look-behind depth. Lower = more random, higher = more similar to seed names.
   * @return {@link String} Name generated by {@link MarkovChain}.
   */
  String makeName(int depth) {
    return markovChain.generate(depth);
  }

  /**
   * Generates a name from the {@link MarkovChain}, with default look-behind of 2.
   *
   * @return {@link String} Name generated by {@link MarkovChain}.
   */
  String makeName() {
    return makeName(random.nextInt(2) + 2);
  }
}
